### ISSUE TITLE
Practica

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/practica-de-proceso-de-negocio-team-pro#1]
[Team pro1.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-proceso-de-negocio-team-pro/files/7369074/Team.pro1.pdf)

**Comment by ArturoAngonJose** [comment]
Calificación:  17/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
